apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: todo-frontend
        image: 904382896645.dkr.ecr.us-west-2.amazonaws.com/mern-app-repo/client:latest 
        ports:
        - containerPort: 80
        env:
        - name: VITE_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: todo-app-config
              key: api-url
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"