apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-gp2
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer