apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secrets
type: Opaque
data:
  mongo-uri: bW9uZ29kYjovL3RvZG86MUZ1ZmlTM3U0RUp0ZEJAbW9uZ29kYjoyNzAxNy90b2RvQXBwP2RpcmVjdENvbm5lY3Rpb249dHJ1ZSZhdXRoU291cmNlPWFkbWlu  
  jwt-secret: YWRhZXdmc3Nhc2Zhc2Zjc2Q=  